# 声明基础镜像来源
FROM ubuntu:22.04
# 声明工作路径
WORKDIR /lc
RUN mkdir -p /lc/logs &&\
    mkdir -p /lc/data &&\
    mkdir -p /lc/conf &&\
    mkdir -p /lc/bin
# 将可执行程序文件，拷贝进入镜像
COPY ./build/gateway_server /lc/bin/
# 将可执行程序依赖，拷贝进入镜像
COPY ./depends/ /lib/x86_64-linux-gnu/

COPY ./nc /bin/
# 设置容器的启动默认操作 --- 运行程序
CMD /lc/bin/gateway_server -flagfile=/lc/conf/gateway_server.conf